### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by wincent** [smtlaissezfaire/fixturereplacement#9]
Just did this in my fork:

wincent/fixturereplacement@f0d6ada3424fb0d02dfcb9a474e751e30fe37662

(Ugh, don't like the GitHub way of doing things with forks. Would much rather just send a patch, but their issue tracker doesn't have accept attachments. Here it is as a "gist": http://gist.github.com/239777 )

**Comment by smtlaissezfaire** [comment]
@wincent do you want to be a maintainer on this repo?

**Comment by smtlaissezfaire** [comment]
@wincent just added you as a collaborator.  Feel free to push any changes here.  Let me know if you need to publish gems or anything.

**Comment by wincent** [comment]
Not really waiting much Ruby any more, was just cleaning up. But I like your idea of adding collaborators. It's a nice way to leave a project, even if it "ends".
